### PR TITLE
Make continuation `FnOnce`

### PR DESCRIPTION
**Pull request by WaffleLapkin**
This generally makes code a little bit nicer

### CODE REVIEW

**Review by Hirrolot — COMMENTED** [review]
This is a breaking change, right?

**Comment by WaffleLapkin** [comment]
Yes, this is a breaking change.

**Comment by Hirrolot** [comment]
The only reason to make the change is to structure the code in the library with less hassle? In Rust, we normally expose the most generic function type to library users, which is `Fn` in our case. Yes, `FnOnce` may look nicer in the library bowels, but I don't think we should introduce this change for just this reason. In addition, this would break someone's code.

**Comment by WaffleLapkin** [comment]
While it's true that this change makes __calling__ the continuation **more** restrictive, at the same time it makes __writing__ the continuation a lot **less** restrictive. We lose ability to call continuation multiple times (that we didn't use anyway) but gain ability to move stuff into the closure, to set flags from inside it, etc. There really isn't any reason for the continuation to be `Fn`.

> [...] the most generic function type to library users, which is Fn in our case

Not really, as said before: it's more permissive to call, but not to provide.

> In addition, this would break someone's code.

While this could of course be the case, this is highly unlikely. For this change to break something a user would need to be writing their own handlers (instead of using tools provided by this library) **and** calling the continuation multiple times (`Fn` is trivially `FnOnce` so providing continuation can't be broken).

**Review by Hirrolot — CHANGES_REQUESTED** [review]
Yes, sorry, I forgot for a minute that the hierarchy if functions if `FnOnce` : `FnMut` : `Fn`, not the opposite.

The only missing change is updating `CHANGELOG.md`.

**Review by Hirrolot — APPROVED** [review]

**Pull request merged**
